# Be sure to restart your server when you modify this file.

# Usage:  Rails.application.secrets.domain_name
# 
development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: 52126df2c91e5301ab806a8002c396736b88742d2b339d58c6cd1307e52a46493b83f86eb4cf4a95f6d44f557a938d1ababb5226bcf946793e7c5f0202c11616

  qiniu_access_key: hxrvqoedfaizpmzdanxsmiotx60zwudxaseybfcx
  qiniu_secret_key: n886ogk5iguwyx-m4m-nlsap0-otgd2_eccsqid_

test:
  domain_name: example.com 
  secret_key_base: 3199b75cc85685b948c63140008d312fafffa981f3a5a4e67f98bd606d37f90f67c471ffc8497462875e36731b00dffc3818d9452c39c6054944a7ddc9e5c14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #
  site_name: wedxt.com
  host_name: http://www.wedxt.com
  #asset host for template
  assets_host: http://www.wedxt.cn

  host_name_dev: http://localhost:3000
  assets_host_dev: http://www.wedxt.cn

  #send email
  gmail_username: kenrome
  gmail_password: kenrome001

  qmail_username: kenrome@qq.com
  qmail_password: inruby.com

  mailgun_username: postmaster@yufuwu.cn
  mailgun_password: 0u70aogv2od1

  #use on email
  domain_name: wedxt.com

  #admin
  admin_name: master
  admin_email: master@inruby.com
  admin_password: kenrome
  roles: [admin, user, vip]

  #send sms
  sms_bao_user: inruby
  sms_bao_password: kenrome001
  sms_max_character_count: 64

  #send sms
  #admin_phone: 18080810818|18280673990
  admin_phone: 18080810818

  #qiniu store
  qiniu_access_key: hxrvqoedfaizpmzdanxsmiotx60zwudxaseybfcx
  qiniu_secret_key: n886ogk5iguwyx-m4m-nlsap0-otgd2_eccsqid_

  #
  #alipay
  alipay_pid: 2088302301804692
  alipay_key: fohwoskwcoielankuxmnx08h313utoqn
  alipay_seller_email: 77632132@qq.com

  #payment 
  price_base: 60
  price_vip: 380
  price_biz: 2000

  #the max upload image count
  max_image_count: 20

  #omniauth
  tqq_key: 101148468
  tqq_securt: 861e30f9adefb07ea5485ecd0f3308a9
  douban_key: 0274327485d6e040075c975d9184a0c0
  douban_securt: 1418e19127eff6b7
  weibo_key: 1246564545
  weibo_securt: 8260eabda40382558c997c969d618c78
